# Generated by Django 4.0 on 2023-07-14 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaFerramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.SmallIntegerField(blank=True, default=2023, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='livros/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Paperback', 'Paperback'), ('Hardcover', 'Hardcover')], default='Paperback', max_length=20, null=True)),
                ('editora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='listaferramentas.listaferramenta')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
