# Generated by Django 4.0 on 2023-07-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaferramentas', '0002_remove_ferramenta_editora_remove_ferramenta_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
