# Generated by Django 4.2.3 on 2023-07-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editora',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['titulo']},
        ),
        migrations.AddField(
            model_name='livro',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Paperback', 'Paperback'), ('Hardcover', 'Hardcover')], max_length=20, null=True),
        ),
    ]
