# Generated by Django 4.2.2 on 2023-07-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_alter_livro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano',
            field=models.SmallIntegerField(blank=True, default=2023, null=True),
        ),
    ]
