# Generated by Django 4.2.2 on 2023-07-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0002_alter_livro_options_livro_tipo_alter_livro_ano'),
        ('livraria', '0004_alter_livro_ano'),
    ]

    operations = [
    ]
