# Generated by Django 4.0 on 2023-07-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_alter_livro_ano_alter_livro_tipo'),
        ('livraria', '0005_merge_20230707_1139'),
    ]

    operations = [
    ]
