# Generated by Django 4.0 on 2023-07-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_pessoa_options_alter_pessoa_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={},
        ),
        migrations.AlterModelManagers(
            name='pessoa',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='username',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(default='1999-01-01'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cargo',
            field=models.CharField(choices=[('electricista', 'Electricista'), ('serralheiro', 'Serralheiro'), ('ajudante', 'Ajudante'), ('instrumentista', 'Instrumentista'), ('outro', 'Outro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
