# Generated by Django 4.0 on 2023-07-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_pessoa_options_alter_pessoa_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
